server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        # Le decimos que busque primero el index.csr.html
        index index.csr.html index.html index.htm;
        # Si el usuario recarga la página, lo mandamos al index.csr.html
        try_files $uri $uri/ /index.csr.html;
    }
}